# Generated by Django 3.0.2 on 2021-04-24 23:42

from django.db import migrations, models
import songs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('key', models.CharField(blank=False, max_length=3)),
                ('ytlink', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.CharField(max_length=100)),
                ('bpm', models.IntegerField()),
                ('have_track', models.BooleanField()),
                ('tracklink', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
