# Generated by Django 3.0.2 on 2021-04-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='ytlink',
            field=models.CharField(max_length=60),
        ),
    ]
