# Generated by Django 3.0.2 on 2021-04-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20210427_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
