# Generated by Django 3.0.2 on 2021-04-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20210427_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='tracklink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='ytlink',
            field=models.CharField(max_length=100),
        ),
    ]
