# Generated by Django 3.2.7 on 2021-12-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_remove_song_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.ManyToManyField(to='songs.Categories'),
        ),
    ]
