# Generated by Django 3.2.7 on 2021-12-16 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_delete_categoriesofsong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.key'),
        ),
    ]
