# Generated by Django 4.0.4 on 2022-04-28 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_alter_song_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.categories')),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.ManyToManyField(through='songs.SongCategory', to='songs.categories'),
        ),
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Key',
        ),
        migrations.AddField(
            model_name='songcategory',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song'),
        ),
    ]
