# Generated by Django 4.0.4 on 2022-04-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_songcategory_alter_song_category_alter_song_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.ManyToManyField(to='songs.categories'),
        ),
        migrations.DeleteModel(
            name='SongCategory',
        ),
    ]
