# Generated by Django 4.0.4 on 2022-04-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0013_alter_categories_id_alter_song_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
